option(LIBIGL_WITH_COMISO OFF)
option(LIBIGL_WITH_EMBREE OFF)
option(LIBIGL_WITH_OPENGL ON)
option(LIBIGL_WITH_OPENGL_GLFW ON)
option(LIBIGL_WITH_OPENGL_GLFW_IMGUI OFF)
option(LIBIGL_WITH_PNG OFF)
option(LIBIGL_WITH_TETGEN OFF)
option(LIBIGL_WITH_TRIANGLE OFF)
option(LIBIGL_WITH_PREDICATES OFF)
option(LIBIGL_WITH_XML OFF)
option(LIBIGL_WITH_PYTHON OFF)
ExternalProject_Add(
        libigl
        GIT_REPOSITORY ${LINK_HEADER}github.com${SEPARATE_FLAG}libigl/libigl.git
        GIT_TAG v2.3.0
#        GIT_TAG 79dc4f683877a8bb4eaf63620437a5454f6c47c1
        CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${EXTERNAL_INSTALL_DIR}
#            -DLIBIGL_USE_STATIC_LIBRARY=ON
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        PREFIX ${EXTERNAL_PREFIX}/libigl
)