option(BUILD_SHARED_LIBS OFF)
option(ASSIMP_BUILD_TESTS OFF)
option(ASSIMP_BUILD_ASSIMP_TOOLS OFF)
option(ASSIMP_BUILD_ZLIB ON)
option(ASSIMP_NO_EXPORT ON)
option(ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT OFF)
ExternalProject_Add(
        assimp
        GIT_REPOSITORY ${LINK_HEADER}github.com${SEPARATE_FLAG}assimp/assimp.git
        GIT_TAG a214b0833f368d665f25d296385966bbc13a796b
        CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${EXTERNAL_INSTALL_DIR}
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DBUILD_SHARED_LIBS=OFF
        PREFIX ${EXTERNAL_PREFIX}/assimp
)